#!/bin/bash
#Script to do simple calc using read commandd
read -p "Pl type 1st val: " a
read -p "Pl type 2nd val: " b

echo "Add=$(($a+$b))"
echo "Sub=$(($a-$b))"
echo "Mul=$(($a*$b))"
echo "Div=$(($a/$b))"
